config_version = 12

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.69999998435378075
    color = "primary"
    font_weight = 700
    start = [ "launcher", "wallpaper", "workspaces", "spacer_2", "privacy" ]
    widget_spacing = 9

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005"
]

    [desktop_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 64.0
    box_width = 1920.0
    cx = 960.0
    cy = 1048.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        background_color = "on_error"
        background_opacity = 0.0
        background_padding = 0
        background_radius = 12
        bands = 84
        centered = false
        color_1 = "on_surface"
        color_2 = "primary"
        mirrored = true
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 64.0
    box_width = 1920.0
    cx = 960.0
    cy = 68.0
    flip_y = true
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_color = "on_error"
        background_opacity = 0.0
        background_padding = 0
        background_radius = 12
        bands = 84
        centered = false
        color_1 = "on_surface"
        color_2 = "primary"
        mirrored = true
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 168.0
    box_width = 384.0
    cx = 960.0
    cy = 240.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = false
        center_text = true
        clock_style = "digital"
        font_family = "JetBrainsMono Nerd Font"
        format = "{:%H:%M}"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 48.0
    box_width = 192.0
    cx = 960.0
    cy = 324.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = false
        center_text = false
        font_family = "AtkynsonMono NFP Medium"
        format = "{:%d/%m/%y}"

[location]
auto_locate = true
custom_schedule = true
sunrise = "05:00"
sunset = "00:00"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 818.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_day = 6000
temperature_night = 5100

[plugin_settings."noctalia/mpvpaper"]
video_directory = "/home/quang-tran/Videos"

[plugins]
enabled = []

[shell]
lang = "en"

    [shell.screen_corners]
    enabled = true
    size = 30

[theme]
builtin = "Noctalia"
community_palette = "Catppuccin Mocha Blue"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "cava" ]

[wallpaper]
directory = "/home/quang-tran/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/quang-tran/Pictures/Wallpapers/3.jpg"

    [wallpaper.last]
    path = "/home/quang-tran/Pictures/Wallpapers/3.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/quang-tran/Pictures/Wallpapers/3.jpg"

    [[wallpaper.favorite]]
    path = "/home/quang-tran/Pictures/Wallpaper/4.jpg"
    theme_mode = "auto"

[widget.audio_visualizer]
bands = 10
centered = false
interactive = false
width = 82

[widget.clock]
font_family = "JetBrains Mono"
font_weight = 700
format = "{:%a %d %b %H:%M}"

[widget.spacer_2]
type = "spacer"

[widget.workspaces]
labels_only_when_occupied = true