-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

require("config.variables")
require("config.monitors")
require("config.environment")
require("config.permissions")
require("config.autostart")
require("config.window_rule")

require("config.look.colors")
require("config.look.general")
require("config.look.decoration")
require("config.look.animations")
require("config.look.layouts")
require("config.look.misc")
require("config.input.keyboard")
require("config.input.touchpad")
require("config.input.gestures")
require("config.input.devices")
require("config.keybindings.modkey")
require("config.keybindings.apps")
require("config.keybindings.window")
require("config.keybindings.focus")
require("config.keybindings.workspaces")
require("config.keybindings.mouse")
require("config.keybindings.media")

require("config.keybindings.screenshot")
